### ISSUE TITLE
大佬，有没有兴趣来个视频教程？

### ISSUE THREAD

**Issue by 0xbul1** [teojs/Xiaomi-Air-i7-8550u-EFI#1]

**Comment by teojs** [comment]
不好意思，我也是半路出家，一知半解，不想误人子弟，等我之后精通了，会考虑出一个

**Comment by 0xbul1** [comment]
> 不好意思，我也是半路出家，一知半解，不想误人子弟，等我之后精通了，会考虑出一个

大佬厉害啊 ，期待你的教程早日出现，等你！
